version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U user -d school_db" ]
        interval: 3s
        timeout: 3s
        retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_DSN=postgres://user:password@db:5432/school_db?sslmode=disable

volumes:
  pgdata: